# Generated by Django 5.0.3 on 2024-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=10
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("SRC", "采购部门"),
                            ("PRD", "生产部门"),
                            ("MTD", "维修部门"),
                            ("SALE", "销售部门"),
                            ("QA", "质量部门"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("C", "Commissioner"),
                            ("M", "Manager"),
                            ("E", "Engineer"),
                            ("S", "Staff"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matirial",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("matirial_id", models.CharField(max_length=20, unique=True)),
                ("purchase_date", models.DateField()),
                ("matirail_Qualify", models.BooleanField()),
                ("matriaial_QAid", models.CharField(max_length=20)),
                ("message", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Out",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("out_id", models.CharField(max_length=20, unique=True)),
                ("out_date", models.DateField()),
                ("out_qualify", models.CharField(max_length=50)),
                ("out_QAid", models.CharField(max_length=20)),
                ("message", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("message", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WareHousing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("warhousing_id", models.CharField(max_length=20, unique=True)),
                ("produce_date", models.DateField()),
                ("finish_date", models.DateField()),
                ("qualify", models.CharField(max_length=50)),
                ("warehousing_QAid", models.CharField(max_length=20)),
                ("message", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=20)),
            ],
        ),
    ]
