# Generated by Django 5.0.3 on 2024-03-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matirial",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="out",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="warehousing",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[("C", "总监"), ("M", "经理"), ("E", "工程师"), ("S", "员工")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="matirial",
            name="matirail_Qualify",
            field=models.BooleanField(default=False),
        ),
    ]
