# Generated by Django 5.0.3 on 2024-03-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0003_alter_employee_position_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matirial",
            old_name="matriaial_QAid",
            new_name="matirail_QAid",
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(
                choices=[
                    ("SRC", "采购部门"),
                    ("PRD", "生产部门"),
                    ("MTD", "维修部门"),
                    ("SALE", "销售部门"),
                    ("QA", "质检部门"),
                ],
                max_length=100,
            ),
        ),
    ]
