# Generated by Django 5.0.3 on 2024-03-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0004_rename_matriaial_qaid_matirial_matirail_qaid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matirial",
            name="matirail_QAid",
            field=models.CharField(max_length=40),
        ),
    ]
